### ISSUE TITLE
Matchers won’t be available when using Capybara master (future capybara 2.0)

### ISSUE THREAD

**Issue by elabs-dev** [elabs/elabs_matchers#3]
Currently, the matchers attach themselves to rspec for specs of [`:type => :request`](https://github.com/elabs/elabs_matchers/blob/master/lib/elabs_matchers/matchers/have_form_errors_on.rb#L4). However, [Capybara 2.0 have changed the type to :feature](https://github.com/jnicklas/capybara/pull/809), so the current Capybara master (not the beta) will not have the matchers available.

**Comment by jnicklas** [comment]
This has been resolved for like… years.
